// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// GetBoardListReader is a Reader for the GetBoardList structure.
type GetBoardListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBoardListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBoardListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBoardListOK creates a GetBoardListOK with default headers values
func NewGetBoardListOK() *GetBoardListOK {
	return &GetBoardListOK{}
}

/* GetBoardListOK describes a response with status code 200, with default header values.

Success
*/
type GetBoardListOK struct {
	Payload []*models.Board
}

func (o *GetBoardListOK) Error() string {
	return fmt.Sprintf("[GET /boards][%d] getBoardListOK  %+v", 200, o.Payload)
}
func (o *GetBoardListOK) GetPayload() []*models.Board {
	return o.Payload
}

func (o *GetBoardListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
