// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBoardListParams creates a new GetBoardListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBoardListParams() *GetBoardListParams {
	return &GetBoardListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBoardListParamsWithTimeout creates a new GetBoardListParams object
// with the ability to set a timeout on a request.
func NewGetBoardListParamsWithTimeout(timeout time.Duration) *GetBoardListParams {
	return &GetBoardListParams{
		timeout: timeout,
	}
}

// NewGetBoardListParamsWithContext creates a new GetBoardListParams object
// with the ability to set a context for a request.
func NewGetBoardListParamsWithContext(ctx context.Context) *GetBoardListParams {
	return &GetBoardListParams{
		Context: ctx,
	}
}

// NewGetBoardListParamsWithHTTPClient creates a new GetBoardListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBoardListParamsWithHTTPClient(client *http.Client) *GetBoardListParams {
	return &GetBoardListParams{
		HTTPClient: client,
	}
}

/* GetBoardListParams contains all the parameters to send to the API endpoint
   for the get board list operation.

   Typically these are written to a http.Request.
*/
type GetBoardListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get board list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBoardListParams) WithDefaults() *GetBoardListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get board list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBoardListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get board list params
func (o *GetBoardListParams) WithTimeout(timeout time.Duration) *GetBoardListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get board list params
func (o *GetBoardListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get board list params
func (o *GetBoardListParams) WithContext(ctx context.Context) *GetBoardListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get board list params
func (o *GetBoardListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get board list params
func (o *GetBoardListParams) WithHTTPClient(client *http.Client) *GetBoardListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get board list params
func (o *GetBoardListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBoardListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
