// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// GetBoardsReader is a Reader for the GetBoards structure.
type GetBoardsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBoardsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBoardsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBoardsOK creates a GetBoardsOK with default headers values
func NewGetBoardsOK() *GetBoardsOK {
	return &GetBoardsOK{}
}

/* GetBoardsOK describes a response with status code 200, with default header values.

Get the list of boards
*/
type GetBoardsOK struct {
	Payload []*models.Board
}

func (o *GetBoardsOK) Error() string {
	return fmt.Sprintf("[GET /boards][%d] getBoardsOK  %+v", 200, o.Payload)
}
func (o *GetBoardsOK) GetPayload() []*models.Board {
	return o.Payload
}

func (o *GetBoardsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
