// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostBoardsTagIDReader is a Reader for the PostBoardsTagID structure.
type PostBoardsTagIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBoardsTagIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostBoardsTagIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostBoardsTagIDOK creates a PostBoardsTagIDOK with default headers values
func NewPostBoardsTagIDOK() *PostBoardsTagIDOK {
	return &PostBoardsTagIDOK{}
}

/* PostBoardsTagIDOK describes a response with status code 200, with default header values.

Upload a new cover image
*/
type PostBoardsTagIDOK struct {
}

func (o *PostBoardsTagIDOK) Error() string {
	return fmt.Sprintf("[POST /boards/{tagId}][%d] postBoardsTagIdOK ", 200)
}

func (o *PostBoardsTagIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
