// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostBoardsTagIDParams creates a new PostBoardsTagIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostBoardsTagIDParams() *PostBoardsTagIDParams {
	return &PostBoardsTagIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostBoardsTagIDParamsWithTimeout creates a new PostBoardsTagIDParams object
// with the ability to set a timeout on a request.
func NewPostBoardsTagIDParamsWithTimeout(timeout time.Duration) *PostBoardsTagIDParams {
	return &PostBoardsTagIDParams{
		timeout: timeout,
	}
}

// NewPostBoardsTagIDParamsWithContext creates a new PostBoardsTagIDParams object
// with the ability to set a context for a request.
func NewPostBoardsTagIDParamsWithContext(ctx context.Context) *PostBoardsTagIDParams {
	return &PostBoardsTagIDParams{
		Context: ctx,
	}
}

// NewPostBoardsTagIDParamsWithHTTPClient creates a new PostBoardsTagIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostBoardsTagIDParamsWithHTTPClient(client *http.Client) *PostBoardsTagIDParams {
	return &PostBoardsTagIDParams{
		HTTPClient: client,
	}
}

/* PostBoardsTagIDParams contains all the parameters to send to the API endpoint
   for the post boards tag ID operation.

   Typically these are written to a http.Request.
*/
type PostBoardsTagIDParams struct {

	// Cover.
	Cover runtime.NamedReadCloser

	// TagID.
	TagID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post boards tag ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBoardsTagIDParams) WithDefaults() *PostBoardsTagIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post boards tag ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostBoardsTagIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post boards tag ID params
func (o *PostBoardsTagIDParams) WithTimeout(timeout time.Duration) *PostBoardsTagIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post boards tag ID params
func (o *PostBoardsTagIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post boards tag ID params
func (o *PostBoardsTagIDParams) WithContext(ctx context.Context) *PostBoardsTagIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post boards tag ID params
func (o *PostBoardsTagIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post boards tag ID params
func (o *PostBoardsTagIDParams) WithHTTPClient(client *http.Client) *PostBoardsTagIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post boards tag ID params
func (o *PostBoardsTagIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCover adds the cover to the post boards tag ID params
func (o *PostBoardsTagIDParams) WithCover(cover runtime.NamedReadCloser) *PostBoardsTagIDParams {
	o.SetCover(cover)
	return o
}

// SetCover adds the cover to the post boards tag ID params
func (o *PostBoardsTagIDParams) SetCover(cover runtime.NamedReadCloser) {
	o.Cover = cover
}

// WithTagID adds the tagID to the post boards tag ID params
func (o *PostBoardsTagIDParams) WithTagID(tagID string) *PostBoardsTagIDParams {
	o.SetTagID(tagID)
	return o
}

// SetTagID adds the tagId to the post boards tag ID params
func (o *PostBoardsTagIDParams) SetTagID(tagID string) {
	o.TagID = tagID
}

// WriteToRequest writes these params to a swagger request
func (o *PostBoardsTagIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param cover
	if err := r.SetFileParam("cover", o.Cover); err != nil {
		return err
	}

	// path param tagId
	if err := r.SetPathParam("tagId", o.TagID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
