// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// PostBoardsReader is a Reader for the PostBoards structure.
type PostBoardsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBoardsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostBoardsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPostBoardsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostBoardsOK creates a PostBoardsOK with default headers values
func NewPostBoardsOK() *PostBoardsOK {
	return &PostBoardsOK{}
}

/* PostBoardsOK describes a response with status code 200, with default header values.

Update a board
*/
type PostBoardsOK struct {
	Payload *models.UpdateBoard
}

func (o *PostBoardsOK) Error() string {
	return fmt.Sprintf("[POST /boards][%d] postBoardsOK  %+v", 200, o.Payload)
}
func (o *PostBoardsOK) GetPayload() *models.UpdateBoard {
	return o.Payload
}

func (o *PostBoardsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UpdateBoard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostBoardsForbidden creates a PostBoardsForbidden with default headers values
func NewPostBoardsForbidden() *PostBoardsForbidden {
	return &PostBoardsForbidden{}
}

/* PostBoardsForbidden describes a response with status code 403, with default header values.

the board id passed doesn’t match the logged-in user id
*/
type PostBoardsForbidden struct {
}

func (o *PostBoardsForbidden) Error() string {
	return fmt.Sprintf("[POST /boards][%d] postBoardsForbidden ", 403)
}

func (o *PostBoardsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
