// Code generated by go-swagger; DO NOT EDIT.

package boards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// NewUpdateBoardParams creates a new UpdateBoardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateBoardParams() *UpdateBoardParams {
	return &UpdateBoardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBoardParamsWithTimeout creates a new UpdateBoardParams object
// with the ability to set a timeout on a request.
func NewUpdateBoardParamsWithTimeout(timeout time.Duration) *UpdateBoardParams {
	return &UpdateBoardParams{
		timeout: timeout,
	}
}

// NewUpdateBoardParamsWithContext creates a new UpdateBoardParams object
// with the ability to set a context for a request.
func NewUpdateBoardParamsWithContext(ctx context.Context) *UpdateBoardParams {
	return &UpdateBoardParams{
		Context: ctx,
	}
}

// NewUpdateBoardParamsWithHTTPClient creates a new UpdateBoardParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateBoardParamsWithHTTPClient(client *http.Client) *UpdateBoardParams {
	return &UpdateBoardParams{
		HTTPClient: client,
	}
}

/* UpdateBoardParams contains all the parameters to send to the API endpoint
   for the update board operation.

   Typically these are written to a http.Request.
*/
type UpdateBoardParams struct {

	// UpdateBoard.
	UpdateBoard *models.UpdateBoard

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update board params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBoardParams) WithDefaults() *UpdateBoardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update board params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBoardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update board params
func (o *UpdateBoardParams) WithTimeout(timeout time.Duration) *UpdateBoardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update board params
func (o *UpdateBoardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update board params
func (o *UpdateBoardParams) WithContext(ctx context.Context) *UpdateBoardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update board params
func (o *UpdateBoardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update board params
func (o *UpdateBoardParams) WithHTTPClient(client *http.Client) *UpdateBoardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update board params
func (o *UpdateBoardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUpdateBoard adds the updateBoard to the update board params
func (o *UpdateBoardParams) WithUpdateBoard(updateBoard *models.UpdateBoard) *UpdateBoardParams {
	o.SetUpdateBoard(updateBoard)
	return o
}

// SetUpdateBoard adds the updateBoard to the update board params
func (o *UpdateBoardParams) SetUpdateBoard(updateBoard *models.UpdateBoard) {
	o.UpdateBoard = updateBoard
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBoardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.UpdateBoard != nil {
		if err := r.SetBodyParam(o.UpdateBoard); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
