// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateOrUpdateCollectionReader is a Reader for the CreateOrUpdateCollection structure.
type CreateOrUpdateCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrUpdateCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrUpdateCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateOrUpdateCollectionOK creates a CreateOrUpdateCollectionOK with default headers values
func NewCreateOrUpdateCollectionOK() *CreateOrUpdateCollectionOK {
	return &CreateOrUpdateCollectionOK{}
}

/* CreateOrUpdateCollectionOK describes a response with status code 200, with default header values.

Success
*/
type CreateOrUpdateCollectionOK struct {
}

func (o *CreateOrUpdateCollectionOK) Error() string {
	return fmt.Sprintf("[POST /collections][%d] createOrUpdateCollectionOK ", 200)
}

func (o *CreateOrUpdateCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
