// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// NewCreateOrUpdateCollectionParams creates a new CreateOrUpdateCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateOrUpdateCollectionParams() *CreateOrUpdateCollectionParams {
	return &CreateOrUpdateCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrUpdateCollectionParamsWithTimeout creates a new CreateOrUpdateCollectionParams object
// with the ability to set a timeout on a request.
func NewCreateOrUpdateCollectionParamsWithTimeout(timeout time.Duration) *CreateOrUpdateCollectionParams {
	return &CreateOrUpdateCollectionParams{
		timeout: timeout,
	}
}

// NewCreateOrUpdateCollectionParamsWithContext creates a new CreateOrUpdateCollectionParams object
// with the ability to set a context for a request.
func NewCreateOrUpdateCollectionParamsWithContext(ctx context.Context) *CreateOrUpdateCollectionParams {
	return &CreateOrUpdateCollectionParams{
		Context: ctx,
	}
}

// NewCreateOrUpdateCollectionParamsWithHTTPClient creates a new CreateOrUpdateCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateOrUpdateCollectionParamsWithHTTPClient(client *http.Client) *CreateOrUpdateCollectionParams {
	return &CreateOrUpdateCollectionParams{
		HTTPClient: client,
	}
}

/* CreateOrUpdateCollectionParams contains all the parameters to send to the API endpoint
   for the create or update collection operation.

   Typically these are written to a http.Request.
*/
type CreateOrUpdateCollectionParams struct {

	// CreateOrUpdateCollection.
	CreateOrUpdateCollection *models.CreateCollectionFeed

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create or update collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrUpdateCollectionParams) WithDefaults() *CreateOrUpdateCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create or update collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrUpdateCollectionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create or update collection params
func (o *CreateOrUpdateCollectionParams) WithTimeout(timeout time.Duration) *CreateOrUpdateCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create or update collection params
func (o *CreateOrUpdateCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create or update collection params
func (o *CreateOrUpdateCollectionParams) WithContext(ctx context.Context) *CreateOrUpdateCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create or update collection params
func (o *CreateOrUpdateCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create or update collection params
func (o *CreateOrUpdateCollectionParams) WithHTTPClient(client *http.Client) *CreateOrUpdateCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create or update collection params
func (o *CreateOrUpdateCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateOrUpdateCollection adds the createOrUpdateCollection to the create or update collection params
func (o *CreateOrUpdateCollectionParams) WithCreateOrUpdateCollection(createOrUpdateCollection *models.CreateCollectionFeed) *CreateOrUpdateCollectionParams {
	o.SetCreateOrUpdateCollection(createOrUpdateCollection)
	return o
}

// SetCreateOrUpdateCollection adds the createOrUpdateCollection to the create or update collection params
func (o *CreateOrUpdateCollectionParams) SetCreateOrUpdateCollection(createOrUpdateCollection *models.CreateCollectionFeed) {
	o.CreateOrUpdateCollection = createOrUpdateCollection
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrUpdateCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CreateOrUpdateCollection != nil {
		if err := r.SetBodyParam(o.CreateOrUpdateCollection); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
