// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/linbuxiao/go-feedly/models"
)

// GetFeedCollectionsReader is a Reader for the GetFeedCollections structure.
type GetFeedCollectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFeedCollectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFeedCollectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFeedCollectionsOK creates a GetFeedCollectionsOK with default headers values
func NewGetFeedCollectionsOK() *GetFeedCollectionsOK {
	return &GetFeedCollectionsOK{}
}

/* GetFeedCollectionsOK describes a response with status code 200, with default header values.

Success
*/
type GetFeedCollectionsOK struct {
	Payload []*models.Collection
}

func (o *GetFeedCollectionsOK) Error() string {
	return fmt.Sprintf("[GET /collections][%d] getFeedCollectionsOK  %+v", 200, o.Payload)
}
func (o *GetFeedCollectionsOK) GetPayload() []*models.Collection {
	return o.Payload
}

func (o *GetFeedCollectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
