// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetFeedCollectionsParams creates a new GetFeedCollectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFeedCollectionsParams() *GetFeedCollectionsParams {
	return &GetFeedCollectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeedCollectionsParamsWithTimeout creates a new GetFeedCollectionsParams object
// with the ability to set a timeout on a request.
func NewGetFeedCollectionsParamsWithTimeout(timeout time.Duration) *GetFeedCollectionsParams {
	return &GetFeedCollectionsParams{
		timeout: timeout,
	}
}

// NewGetFeedCollectionsParamsWithContext creates a new GetFeedCollectionsParams object
// with the ability to set a context for a request.
func NewGetFeedCollectionsParamsWithContext(ctx context.Context) *GetFeedCollectionsParams {
	return &GetFeedCollectionsParams{
		Context: ctx,
	}
}

// NewGetFeedCollectionsParamsWithHTTPClient creates a new GetFeedCollectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFeedCollectionsParamsWithHTTPClient(client *http.Client) *GetFeedCollectionsParams {
	return &GetFeedCollectionsParams{
		HTTPClient: client,
	}
}

/* GetFeedCollectionsParams contains all the parameters to send to the API endpoint
   for the get feed collections operation.

   Typically these are written to a http.Request.
*/
type GetFeedCollectionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get feed collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeedCollectionsParams) WithDefaults() *GetFeedCollectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get feed collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFeedCollectionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get feed collections params
func (o *GetFeedCollectionsParams) WithTimeout(timeout time.Duration) *GetFeedCollectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feed collections params
func (o *GetFeedCollectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feed collections params
func (o *GetFeedCollectionsParams) WithContext(ctx context.Context) *GetFeedCollectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feed collections params
func (o *GetFeedCollectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feed collections params
func (o *GetFeedCollectionsParams) WithHTTPClient(client *http.Client) *GetFeedCollectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feed collections params
func (o *GetFeedCollectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeedCollectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
