// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPersonalCollectionDetailReader is a Reader for the GetPersonalCollectionDetail structure.
type GetPersonalCollectionDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPersonalCollectionDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPersonalCollectionDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPersonalCollectionDetailOK creates a GetPersonalCollectionDetailOK with default headers values
func NewGetPersonalCollectionDetailOK() *GetPersonalCollectionDetailOK {
	return &GetPersonalCollectionDetailOK{}
}

/* GetPersonalCollectionDetailOK describes a response with status code 200, with default header values.

Success
*/
type GetPersonalCollectionDetailOK struct {
}

func (o *GetPersonalCollectionDetailOK) Error() string {
	return fmt.Sprintf("[GET /collections/{collectionId}][%d] getPersonalCollectionDetailOK ", 200)
}

func (o *GetPersonalCollectionDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
