// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPersonalCollectionDetailParams creates a new GetPersonalCollectionDetailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPersonalCollectionDetailParams() *GetPersonalCollectionDetailParams {
	return &GetPersonalCollectionDetailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPersonalCollectionDetailParamsWithTimeout creates a new GetPersonalCollectionDetailParams object
// with the ability to set a timeout on a request.
func NewGetPersonalCollectionDetailParamsWithTimeout(timeout time.Duration) *GetPersonalCollectionDetailParams {
	return &GetPersonalCollectionDetailParams{
		timeout: timeout,
	}
}

// NewGetPersonalCollectionDetailParamsWithContext creates a new GetPersonalCollectionDetailParams object
// with the ability to set a context for a request.
func NewGetPersonalCollectionDetailParamsWithContext(ctx context.Context) *GetPersonalCollectionDetailParams {
	return &GetPersonalCollectionDetailParams{
		Context: ctx,
	}
}

// NewGetPersonalCollectionDetailParamsWithHTTPClient creates a new GetPersonalCollectionDetailParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPersonalCollectionDetailParamsWithHTTPClient(client *http.Client) *GetPersonalCollectionDetailParams {
	return &GetPersonalCollectionDetailParams{
		HTTPClient: client,
	}
}

/* GetPersonalCollectionDetailParams contains all the parameters to send to the API endpoint
   for the get personal collection detail operation.

   Typically these are written to a http.Request.
*/
type GetPersonalCollectionDetailParams struct {

	// CollectionID.
	CollectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get personal collection detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPersonalCollectionDetailParams) WithDefaults() *GetPersonalCollectionDetailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get personal collection detail params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPersonalCollectionDetailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) WithTimeout(timeout time.Duration) *GetPersonalCollectionDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) WithContext(ctx context.Context) *GetPersonalCollectionDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) WithHTTPClient(client *http.Client) *GetPersonalCollectionDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCollectionID adds the collectionID to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) WithCollectionID(collectionID string) *GetPersonalCollectionDetailParams {
	o.SetCollectionID(collectionID)
	return o
}

// SetCollectionID adds the collectionId to the get personal collection detail params
func (o *GetPersonalCollectionDetailParams) SetCollectionID(collectionID string) {
	o.CollectionID = collectionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPersonalCollectionDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param collectionId
	if err := r.SetPathParam("collectionId", o.CollectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
